### ISSUE TITLE
Analyses Pane

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#17]
active branch=release/py3/v18.2

active analyses=UW142:D33-01F

description="after finishing the iso evo pipeline, just tried to double dlick on one analysis to recall it-error appeared"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 617, in _handle_recall
    self.recall(new)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\envisage\browser\browser_task.py", line 137, in recall
    self._open_recall_editors(ans)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\envisage\browser\browser_task.py", line 301, in _open_recall_editors
    av.isotope_view.isotope_adapter = self.isotope_adapter
AttributeError: 'NoneType' object has no attribute 'isotope_adapter'

```

**Comment by jirhiker** [comment]
could not replicate. This is likely a symptom of some other issue. look in the log for "sync view ..."

**Comment by aschaen** [comment]
![capture](https://user-images.githubusercontent.com/40218738/53823882-43386a80-3f38-11e9-9d3d-4a2c4a92479e.JPG)

**Comment by aschaen** [comment]
related to this...is it possible to change the default scaling for these define equil plots? below is the code we use. this would prevent us from having to manually rescale each plot for every analysis. 

 axis(bounds); %restrict the axes to limits of data in x and y
       ax=axis;      % get current axis values.  ax= [xmin xmax ymin ymax];
       range=(max(data)-min(data))/5;   % y range is 20% of max(data) - min(data) (data is only unexcluded pts.)
       ud.ax2=[0 max(time) min([data; out.fit(1)])-range max([data; out.fit(1)])+range];  %xmin: t=0 xmax:max(time) ymin:min(data,intercept)-20% of range ymax: max(data,intercept)+20% of range
        axis(ud.ax2); % redraw to axis setting

**Comment by jirhiker** [comment]
WRT the plots being cut off can you not make the entire window larger? 

WRT scaling what is wrong with the how the plots are currently scaled? They are already scaled to the data

**Comment by aschaen** [comment]
1) no, this is happening when the window is maxed out for our screen

2) the view for some isotopes (40, 39, 36) is too far zoomed out by default, so it makes evaluating the correct equil. time in detail difficult without manually scaling. Manually scaling each of these plots for a whole batch of data would be tedious.

**Comment by jirhiker** [comment]
ok on number 1, ill have to think on the best approach to resolve that. 

2) so Im assuming you want the data scaled to just the signal data? and not the signal and equilibration points. We should discuss this whole variable equilibration time issue in person. I understand using different equilibration times for different valve configurations but not for different intensities (the only way equilibration time could vary by intensity is if you move out of the molecular flow regime and if that happened you'd likely burn out your filament). It just seems that if you took care of setting the equilibration times correctly during data collection you would not have to do it in data reduction (at least not for every analysis). 

Just something to think about. Ill modify the default scaling for the y axis so that it is easier evaluate the eq time. I could also reduce the x scaling also if you want

**Comment by pesobol** [comment]
the y axis scaling you have adapted in define equil. looks good. can you keep this y-axis scaling as is but include all the data on the x-axis? Right now the data is still being cut off at high values in x.

**Comment by aschaen** [comment]
looks good! ok to close
